services:
  static:
    container_name: ddev-${DDEV_SITENAME}-static
    hostname: poc--drupal-static-export-static
    image: nginx:latest
    ports:
      - "127.0.0.1:$DDEV_HOST_HTTP_PORT:80"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
    volumes:
      - "./static/html:/usr/share/nginx/html"
